services:
  gazebo_dwa:
    container_name: llm_dwa
    build: .
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:99
      - TURTLEBOT3_MODEL=burger
    ports:
      - "6080:6080"
    volumes:
      - ./ros2_ws:/workspace/ros2_ws
    command: ["/root/start-novnc.sh"]
